name: mapa_interactivo
description: "Mapa interactivo, agregar marcadores con informacion y busqueda de ubicaciones"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  #google_maps_flutter: ^2.10.0
  http: ^1.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9
  uuid: ^4.2.2
  material_floating_search_bar_2: ^0.5.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/LogoEmpresaFLETX.png

